"""Criacao das tabelas iniciais

Revision ID: debd81f1df52
Revises: 
Create Date: 2025-12-03 20:53:24.494833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'debd81f1df52'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('perfil', sa.Enum('paciente', 'profissional', 'administrador', name='perfil_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email')
    )
    op.create_table('administradores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('endereco', sa.Text(), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('logs_auditoria',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('acao', sa.String(length=255), nullable=True),
    sa.Column('detalhes', sa.Text(), nullable=True),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pacientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('endereco', sa.Text(), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('profissionais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conselho', sa.String(length=50), nullable=False),
    sa.Column('numero_conselho', sa.String(length=50), nullable=False),
    sa.Column('especialidade', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consultas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('profissional_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('hora', sa.Time(), nullable=True),
    sa.Column('status', sa.Enum('agendada', 'concluida', 'cancelada', name='statusenum'), nullable=False),
    sa.Column('tipo', sa.Enum('presencial', 'online', name='tipo_consulta_enum'), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['profissional_id'], ['profissionais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prontuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consulta_id', sa.Integer(), nullable=False),
    sa.Column('anotacoes', sa.Text(), nullable=True),
    sa.Column('prescricao', sa.Text(), nullable=True),
    sa.Column('data_registro', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['consulta_id'], ['consultas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telemedicinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consulta_id', sa.Integer(), nullable=False),
    sa.Column('codigo_sala', sa.String(length=255), nullable=False),
    sa.Column('url_sala', sa.String(length=500), nullable=False),
    sa.Column('iniciada_em', sa.DateTime(), nullable=True),
    sa.Column('encerrada_em', sa.DateTime(), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['consulta_id'], ['consultas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_sala'),
    sa.UniqueConstraint('codigo_sala')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telemedicinas')
    op.drop_table('prontuarios')
    op.drop_table('consultas')
    op.drop_table('profissionais')
    op.drop_table('pacientes')
    op.drop_table('logs_auditoria')
    op.drop_table('administradores')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
